[package]
name = "articlebot"
version = "0.1.0"
authors = ["dmhacker <dmhacker@yahoo.com>"]

[dependencies]
slack = "0.19.0"
reqwest = "0.8.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bson = "0.10.0"
mongodb = "0.3.7"
chrono = "0.4"